# Generated by Django 2.0.5 on 2018-05-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='user_id',
            new_name='user',
        ),
    ]
